[project]
name = "agent-one"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Isaac0424", email = "eodud3858@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
agent-one = "agent_one:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "single_agent",
]
